"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getEnvLabel = exports.getAppEnvLabel = exports.RUNTIME_ENV = exports.REQUEST_TIMEOUT = exports.APP_ENV = exports.API_BASE_MAP = exports.API_BASE = void 0;
var env_1 = require("./env");
Object.defineProperty(exports, "API_BASE", { enumerable: true, get: function () { return env_1.API_BASE; } });
Object.defineProperty(exports, "API_BASE_MAP", { enumerable: true, get: function () { return env_1.API_BASE_MAP; } });
Object.defineProperty(exports, "APP_ENV", { enumerable: true, get: function () { return env_1.APP_ENV; } });
Object.defineProperty(exports, "REQUEST_TIMEOUT", { enumerable: true, get: function () { return env_1.REQUEST_TIMEOUT; } });
Object.defineProperty(exports, "RUNTIME_ENV", { enumerable: true, get: function () { return env_1.RUNTIME_ENV; } });
Object.defineProperty(exports, "getAppEnvLabel", { enumerable: true, get: function () { return env_1.getAppEnvLabel; } });
Object.defineProperty(exports, "getEnvLabel", { enumerable: true, get: function () { return env_1.getEnvLabel; } });
